**NUMPY**

In [2]:
#unpacking tuple
t = (1,2,3)
a,b,c = t
a = 4
b = 5
c = 6
t = (a,b,c)
print(t)

(4, 5, 6)


In [4]:
import numpy as np


In [5]:
arr = np.array([1,2,3,4,5])
print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

In [3]:
import numpy as np
brr = np.array([[9,8,7,6]])
print(brr[0,1])
print(brr.ndim)

8
2


In [9]:
a = np.zeros((2,5))
print(a)
print("\n")
b = np.ones((5,5))
print(b)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [10]:
#just like range function
b = np.arange(0,15,2)
print(b)

[ 0  2  4  6  8 10 12 14]


In [11]:
c = np.linspace(1,5,6)
print(c)

[1.  1.8 2.6 3.4 4.2 5. ]


In [9]:
# 1 se 10 ke beech mein 20 number that have equal difference in each consecutive term
d = np.linspace(1,10,20)
print(d)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [11]:
e = np.empty_like(c)
print(e)

[1. 2. 3. 4. 5.]


In [13]:
i = np.identity(5)
print(i)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [14]:
t = np.arange(99)
print(t)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98]


In [16]:
p = t.reshape(3,33)
print(p)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56
  57 58 59 60 61 62 63 64 65]
 [66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89
  90 91 92 93 94 95 96 97 98]]


In [17]:
p.ravel()
p

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [18]:
f = [[1,2,3],[4,5,6],[7,8,9]]
g = np.array(f)
print(g)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
#adding elements row wise
print(g.sum(axis=0))


#adding elements column wise
print(g.sum(axis=1))


[12 15 18]
[ 6 15 24]


In [21]:
#transpose of array
print(g.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [22]:
print(g.ndim)

2


In [24]:
print(g.size)

9


In [26]:
#max element is at which index position
print(g.argmax())
#min element is at which index position
print(g.argmin())

8
0


In [27]:
#axis0 pe neeche aate waqt har row ke kis index pe max value hai
print(g.argmax(axis = 0)) 

[2 2 2]


In [28]:
#used in making the array straight
print(g.ravel())

[1 2 3 4 5 6 7 8 9]


In [31]:
print(np.sqrt(g))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


In [33]:
print(g)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [34]:
#all sort of positions in array  where element is greater than 5
np.where(g>5)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [35]:
np.where(g>=0)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [18]:
r = np.random.rand(3,4)
r

array([[0.91725109, 0.66038315, 0.56350972, 0.60534849],
       [0.11924793, 0.52647749, 0.56038421, 0.62605831],
       [0.37505417, 0.88105408, 0.26344434, 0.30909789]])

In [19]:
t = np.random.randint(low =4,size=(2,5))
t

array([[3, 1, 0, 0, 0],
       [2, 3, 2, 1, 2]])

In [20]:
p = np.random.rand(3,3)*9+1
p

array([[4.7672383 , 1.09471296, 6.89558059],
       [8.93851074, 5.83197432, 6.19133599],
       [1.6060467 , 3.48203298, 7.56880001]])

In [23]:
arr1 = np.random.randint(low=4,size=(2,2))
arr1


array([[3, 2],
       [2, 0]])

In [24]:
arr1[0][1]

2